{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23415] issue with network connection", "trace": "('/home/den/PycharmProjects/pYtest/tests/users/test_users.py', 13, 'Skipped: [ISSUE-23415] issue with network connection')"}, "start": 1685115589642, "stop": 1685115589642, "uuid": "d671eb5d-5a50-40ac-bc6c-b32262f0b254", "historyId": "19630dc244333b530cc14c893795ee5f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23415] issue with network connection')"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "dencomp"}, {"name": "thread", "value": "133872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}