{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23415] issue with network connection", "trace": "('/home/den/PycharmProjects/pYtest/tests/users/test_users.py', 15, 'Skipped: [ISSUE-23415] issue with network connection')"}, "start": 1685116595522, "stop": 1685116595522, "uuid": "ee033eb6-abb9-426c-bfd8-c0f0bfa9c552", "historyId": "19630dc244333b530cc14c893795ee5f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23415] issue with network connection')"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "dencomp"}, {"name": "thread", "value": "134936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}