{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23415] issue with network connection", "trace": "('/home/den/PycharmProjects/pYtest/tests/users/test_users.py', 15, 'Skipped: [ISSUE-23415] issue with network connection')"}, "description": "\n    Try to check that 1 is equal 2\n\n    ", "start": 1685117407381, "stop": 1685117407381, "uuid": "3b0abf37-997c-46e2-b53a-6074a3580df7", "historyId": "19630dc244333b530cc14c893795ee5f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23415] issue with network connection')"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "dencomp"}, {"name": "thread", "value": "136448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}